### ISSUE TITLE
Using menu without Router

### ISSUE THREAD

**Issue by nKlar** [ShankyTiwari/ng-material-multilevel-menu#59]
Hello!
I want to use the NgMaterialMultilevelMenu in my project without the standard angular router. Is it possible? I will use ui router instead. When I import and start to use the menu I get the following error:
`ERROR NullInjectorError: StaticInjectorError(AppModule)[ListItemComponent -> Router]: 
  StaticInjectorError(Platform: core)[ListItemComponent -> Router]: 
    NullInjectorError: No provider for Router!
    at NullInjector.get (http://localhost:4200/vendor.js:63854:27)
    at resolveToken (http://localhost:4200/vendor.js:65640:24)
    at tryResolveToken (http://localhost:4200/vendor.js:65566:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:65429:20)
    at resolveToken (http://localhost:4200/vendor.js:65640:24)
    at tryResolveToken (http://localhost:4200/vendor.js:65566:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:65429:20)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:89467:29)
    at NgModuleRef_.get (http://localhost:4200/vendor.js:90555:16)
    at resolveDep (http://localhost:4200/vendor.js:91085:45)
View_AppComponent_0 @ AppComponent.html:3
proxyClass @ compiler.js:19436
logError @ core.js:39645
handleError @ core.js:9162
(anonymous) @ core.js:35060
invoke @ zone-evergreen.js:359
run @ zone-evergreen.js:124
runOutsideAngular @ core.js:34121
(anonymous) @ core.js:35057
invoke @ zone-evergreen.js:359
onInvoke @ core.js:34195
invoke @ zone-evergreen.js:358
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:855
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:34176
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:559
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:542
scheduleTask @ zone-evergreen.js:381
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:845
then @ zone-evergreen.js:955
bootstrapModule @ core.js:34951
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:79
0 @ main.ts:12
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
AppComponent.html:3 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 7, nodeDef: {…}, elDef: {…}, elView: {…}}
View_AppComponent_0 @ AppComponent.html:3
proxyClass @ compiler.js:19436
logError @ core.js:39645
handleError @ core.js:9167
(anonymous) @ core.js:35060
invoke @ zone-evergreen.js:359
run @ zone-evergreen.js:124
runOutsideAngular @ core.js:34121
(anonymous) @ core.js:35057
invoke @ zone-evergreen.js:359
onInvoke @ core.js:34195
invoke @ zone-evergreen.js:358
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:855
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:34176
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:559
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:542
scheduleTask @ zone-evergreen.js:381
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:845
then @ zone-evergreen.js:955
bootstrapModule @ core.js:34951
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:79
0 @ main.ts:12
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
main.ts:12 NullInjectorError: StaticInjectorError(AppModule)[ListItemComponent -> Router]: 
  StaticInjectorError(Platform: core)[ListItemComponent -> Router]: 
    NullInjectorError: No provider for Router!
    at NullInjector.get (http://localhost:4200/vendor.js:63854:27)
    at resolveToken (http://localhost:4200/vendor.js:65640:24)
    at tryResolveToken (http://localhost:4200/vendor.js:65566:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:65429:20)
    at resolveToken (http://localhost:4200/vendor.js:65640:24)
    at tryResolveToken (http://localhost:4200/vendor.js:65566:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:65429:20)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:89467:29)
    at NgModuleRef_.get (http://localhost:4200/vendor.js:90555:16)
    at resolveDep (http://localhost:4200/vendor.js:91085:45)`

**Comment by StavM** [comment]
can you create a small [stackblitz ](https://stackblitz.com/) of the issue ?

**Comment by nKlar** [comment]
Of course, here it is.
https://angular-b1h7lb.stackblitz.io
At the moment it is not really an issue for me, because I realized that I don't really need the ui router for angular. I just assumed it, because I came from angularjs.

**Comment by ShankyTiwari** [comment]
Okay, then @nKlar closing the issue and feel free to reopen.
@StavM thanks!

Thanks
